services:
  mysql:
    image: mysql:8.4
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysql_data: